image: Visual Studio 2017
environment:
  matrix:
    - node_version: '8'

install:
- ps: Install-Product node 8 x64
- ps: |
    $destdir = Join-Path $env:appveyor_build_folder 'lib'
    $destfile = Join-Path $destdir 'deps.zip'
    Set-Location $destdir
    Invoke-WebRequest "https://ghfvs-installer.github.com/dependencies/deps.zip" -OutFile $destfile
    &'7z' -bb3 x 'deps.zip'

    Set-Location $env:appveyor_build_folder

    nuget restore

    $patchNumber = $env:APPVEYOR_BUILD_NUMBER
    scripts\Set-Version.ps1 $patchNumber

configuration: Release
build:
  project: GitForUnity.sln
  verbosity: minimal
test:
  assemblies:
    except:
      - '**\*.TestRunner.dll'
      - '**\TestUtils.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor
on_success:
- ps: |

    $version = $env:APPVEYOR_BUILD_VERSION

    Write-Output "Packaging version $($env:GitAssemblyInformationalVersion) ($version)"

    $artifactDir="$($env:appveyor_build_folder)\artifacts"
    $tmpdir="tmp"
    $packageDir="$($env:appveyor_build_folder)\build\packages"
    $srcdir="$($env:appveyor_build_folder)\src"

    $packagename="com.unity.git.api"
    $sourcedir="$packageDir\$packagename"
    $extrasdir="$srcdir\extras\$packagename"
    $ignorefile="$srcdir\$packagename\.npmignore"
    $baseinstall="Packages\$packagename"
    packaging\create-unity-packages\run.ps1 $sourcedir $artifactDir $packagename $version $extrasdir $ignorefile $baseinstall

    $packagename="com.unity.git.ui"
    $sourcedir="$packageDir\$packagename"
    $extrasdir="$srcdir\extras\$packagename"
    $ignorefile="$srcdir\$packagename\.npmignore"
    $baseinstall="Packages\$packagename"
    packaging\create-unity-packages\run.ps1 $sourcedir $artifactDir $packagename $version $extrasdir $ignorefile $baseinstall

    # save commit
    $commitfile="$sourcedir\commit"
    Add-Content $commitfile $appveyor_repo_commit

    $sourcedir="$($env:appveyor_build_folder)\build\Release"
    $dllzip="$artifactDir\binaries-$version.zip"
    Write-Output "Zipping $sourcedir to $dllzip"
    7z a $dllzip $sourcedir

on_finish:
- ps: |
    Set-Location $env:appveyor_build_folder
    Get-ChildItem $env:appveyor_build_folder\build\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName logs }
    Get-ChildItem $env:appveyor_build_folder\artifacts\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName packages }
