image: Visual Studio 2017
environment:
  matrix:
    - node_version: '8'

install:
- ps: |
    $destdir = Join-Path $env:appveyor_build_folder 'lib'
    $destfile = Join-Path $destdir 'deps.zip'
    Set-Location $destdir
    Invoke-WebRequest "https://ghfvs-installer.github.com/dependencies/deps.zip" -OutFile $destfile
    &'7z' -bb3 x 'deps.zip'

    Set-Location $env:appveyor_build_folder

    nuget restore

    $patchNumber = $env:APPVEYOR_BUILD_NUMBER
    scripts\Set-Version.ps1 $patchNumber

configuration: Release
build:
  project: GitForUnity.sln
  verbosity: minimal
test:
  assemblies:
    except:
      - '**\*.TestRunner.dll'
      - '**\TestUtils.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor
on_success:
- ps: |

    Get-ChildItem env:

    $version = $env:APPVEYOR_BUILD_VERSION

    $artifactDir="$($env:appveyor_build_folder)\artifacts"
    $packageDir="$($env:appveyor_build_folder)\build\packages"
    $gitpackage="com.unity.git.api"
    $gituipackage="com.unity.git.ui"

    $packagename=$gitpackage
    $sourcedir="$packageDir\$packagename"
    $extrasdir="$($env:appveyor_build_folder)\src\git-for-unity\extras\$packagename"
    $ignorefile="$sourcedir\.npmignore"
    $baseinstall=""
    packaging\create-unity-packages\run.ps1 $artifactDir $packagename $version $sourcedir $extrasdir $ignorefile $baseinstall

    $packagename=$gituipackage
    $sourcedir="$packageDir\$packagename"
    $extrasdir="$($env:appveyor_build_folder)\src\git-for-unity\extras\$packagename"
    $ignorefile="$sourcedir\.npmignore"
    $baseinstall=""
    packaging\create-unity-packages\run.ps1 $artifactDir $packagename $version $sourcedir $extrasdir $ignorefile $baseinstall

    # save commit
    $commitfile="$sourcedir\commit"
    Add-Content $commitfile $appveyor_repo_commit

    $gitzip="$($env:appveyor_build_folder)\$gitpackage-$version.zip"
    $gituizip="$($env:appveyor_build_folder)\$gituipackage-$version.zip"

    $sourcedir="$packageDir\$gitpackage"
    Write-Output "Zipping $sourcedir to $gitzip"
    7z a $gitzip $sourcedir

    $sourcedir="$packageDir\$gituipackage"
    Write-Output "Zipping $sourcedir to $gitzip"
    7z a $gituizip $sourcedir

    $sourcedir="$($env:appveyor_build_folder)\build\Release"
    $dllzip="$($env:appveyor_build_folder)\binaries-$version.zip"
    Write-Output "Zipping $sourcedir to $dllzip"
    7z a $dllzip $sourcedir

    Write-Output "Uploading $gitzip"
    Push-AppveyorArtifact $gitzip -DeploymentName gitpackage
    Push-AppveyorArtifact $gituizip -DeploymentName gituipackage
    Push-AppveyorArtifact $dllzip -DeploymentName binaries

on_finish:
- ps: |
    Set-Location $env:appveyor_build_folder
    Get-ChildItem $env:appveyor_build_folder\build\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName logs }
    Get-ChildItem $env:appveyor_build_folder\artifacts\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName packages }
