upm_linux:
  type: Unity::VM
  image: package-ci/ubuntu:latest
  flavor: m1.large
test_editors:
  - version: 2019.1
test_platforms:
  - name: ubuntu
    type: Unity::VM
    image: package-ci/ubuntu:latest
    flavor: m1.large
packages:
  - name: com.unity.git.api
    path: PackageSources/com.unity.git.api
