{% metadata_file .yamato_config/configuration.yml %}
---
build:
  name: Build on Windows
  agent:
    type: Unity::VM
    image: core-kaunas/win10-vs2017-dotnetcore:latest
    flavor: m1.large
  interpreter: powershell
  commands:
    - |
      scripts\Get-Deps.ps1
      scripts\Build.ps1
      scripts\Test.ps1 -Yamato

      dotnet tool install --tool-path . nbgv
      Push-Location src\com.unity.git.api
      $version = ..\..\nbgv get-version -f json | ConvertFrom-Json
      Pop-Location

      Write-Output "Packaging version $($version.AssemblyInformationalVersion)"
      scripts\Create-Packages.ps1 $($version.AssemblyInformationalVersion) "PackageSources" -SkipUnity -SkipPackman

    - npm install upm-ci-utils@stable -g --registry https://api.bintray.com/npm/unity/unity-npm
{% for package in packages %}
    - scripts\CreateCombinedManifest.ps1 {{ package.name }} {{ package.path }}
    - Copy-Item upm-ci~\packages\{{ package.name }}*.tgz artifacts\
{% endfor %}

  artifacts:
    packages:
      paths:
        - "artifacts/**/*"
    sources:
      paths:
        - "PackageSources/**/*"
    tests:
      paths:
        - "test-results/**/*"
