build:
  name: Build
  agent:
    type: Unity::VM
    image: industrial/win10-dotnet-builder:latest
    flavor: m1.large
  interpreter: powershell
  commands:
    - scripts\Set-Version.ps1 -BumpPatch -NewVersion $($env:YAMATO_JOB_ID)
    - .\Build.ps1
    - .\Create-Packages.ps1 $($env:GitAssemblyInformationalVersion)
  artifacts:
    packages:
      paths:
        - "artifacts/**/*"
