build:
  name: Build
  agent:
    type: Unity::VM
    image: core-kaunas/win10-vs2017-dotnetcore:latest
    flavor: m1.large
  interpreter: powershell
  commands:
    - |
      $version = $env:YAMATO_JOB_ID
      Write-Output "Building $version"
      scripts\Get-Deps.ps1
      scripts\Set-Version.ps1 $version -BumpPatch -Verbose
      scripts\Build.ps1
      scripts\Create-Packages.ps1 $($env:GitAssemblyInformationalVersion)

  artifacts:
    packages:
      paths:
        - "artifacts/**/*"
